// This file is auto-generated by TanStack Router
// Run `npm run dev` to regenerate it

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as TransactionsRoute } from './routes/transactions'
import { Route as LedgerRoute } from './routes/ledger'
import { Route as TaxRoute } from './routes/tax'
import { Route as ReconciliationRoute } from './routes/reconciliation'
import { Route as AuditRoute } from './routes/audit'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/transactions': {
      preLoaderRoute: typeof TransactionsRoute
      parentRoute: typeof rootRoute
    }
    '/ledger': {
      preLoaderRoute: typeof LedgerRoute
      parentRoute: typeof rootRoute
    }
    '/tax': {
      preLoaderRoute: typeof TaxRoute
      parentRoute: typeof rootRoute
    }
    '/reconciliation': {
      preLoaderRoute: typeof ReconciliationRoute
      parentRoute: typeof rootRoute
    }
    '/audit': {
      preLoaderRoute: typeof AuditRoute
      parentRoute: typeof rootRoute
    }
  }
}

const IndexRouteWithChildren = IndexRoute._addFileChildren([])
const TransactionsRouteWithChildren = TransactionsRoute._addFileChildren([])
const LedgerRouteWithChildren = LedgerRoute._addFileChildren([])
const TaxRouteWithChildren = TaxRoute._addFileChildren([])
const ReconciliationRouteWithChildren = ReconciliationRoute._addFileChildren([])
const AuditRouteWithChildren = AuditRoute._addFileChildren([])

export const routeTree = rootRoute._addFileChildren([
  IndexRouteWithChildren,
  TransactionsRouteWithChildren,
  LedgerRouteWithChildren,
  TaxRouteWithChildren,
  ReconciliationRouteWithChildren,
  AuditRouteWithChildren,
])
